plugins {
    id "com.android.application"
}

android {
    namespace "com.boriken.learner"
    compileSdk 34

    defaultConfig {
        applicationId "com.boriken.learner"
        minSdk 24
        targetSdk 34
        versionCode 32
        versionName "0.3.2"
        resConfigs "en", "es"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            applicationIdSuffix ""
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ["/META-INF/{AL2.0,LGPL2.1}"]
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "androidx.activity:activity:1.8.2"
    implementation "com.google.android.material:material:1.11.0"
}
